name: 每日抓取 Apple ID

on:
  schedule:
    - cron: '0 0 * * *'  # 运行时间仍然是 UTC 时间的 00:00，相当于北京时间 08:00
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    env:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'false'
      PUPPETEER_EXECUTABLE_PATH: ''

    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: 设置 Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: 安装依赖
      run: bun i

    - name: 执行抓取脚本
      run: bun main.ts
      env:
        PUPPETEER_ARGS: '--no-sandbox --disable-setuid-sandbox'

    - name: 检查文件变更并提交
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

        # 添加文件
        git add index.html index.json

        # 检查是否有变更
        if git diff --cached --quiet; then
          echo "❌ 没有检测到文件变更，不提交"
          exit 0
        fi

        # 获取上海时间 (UTC+8)
        SHANGHAI_TIME=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')

        # 提交更改
        git commit -m "自动更新: Apple ID账号列表 [${SHANGHAI_TIME}]"
        
        # 设置 push 远程仓库
        git push origin HEAD:main
        echo "✅ index.html 和 index.json 已更新并提交"
